version: '3'

services:
  rapp:
    image: 127.0.0.1:5000/rstackdemo
    build: .
    ports:
      - "8899:8899"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
  some-redis:
    image: redis:alpine
